[project]
name = "crew_ai_tool"
version = "0.1.0"
description = "Power up your crews with crew_ai_tool"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.203.1"
]

[tool.crewai]
type = "tool"
